#!/bin/bash

# Script para probar la integración de Mercado Pago en ServiHogar
# Ejecutar desde la raíz del proyecto Proyecto/

echo "🔧 Instalando dependencias del backend..."
pip install mercadopago==2.2.3

echo ""
echo "✅ Dependencia instalada"
echo ""
echo "📋 Pasos siguientes:"
echo ""
echo "1. Copia tus credenciales de Mercado Pago:"
echo "   - Ve a: https://www.mercadopago.cl/developers/panel/app"
echo "   - Copia tu 'Access Token de Prueba'"
echo ""
echo "2. Configura tu archivo .env:"
echo "   MERCADOPAGO_ACCESS_TOKEN=TEST-1234567890-XXXXXX-XXXXXXXXXXXXXXXXXXXXXX"
echo "   FRONTEND_URL=http://localhost:5173"
echo ""
echo "3. Reinicia el servidor Django:"
echo "   docker-compose restart web"
echo "   # O si estás en desarrollo local:"
echo "   python manage.py runserver"
echo ""
echo "4. Prueba el flujo completo:"
echo "   - Registra un usuario cliente"
echo "   - Registra un profesional (o usa admin para aprobar rápido)"
echo "   - Como cliente, haz una reserva"
echo "   - Como profesional, confirma la reserva"
echo "   - Como cliente, ve a 'Mis Solicitudes' y haz clic en 'Pagar'"
echo "   - Usa una tarjeta de prueba:"
echo "     * Número: 5416 7526 0258 2580"
echo "     * CVV: 123"
echo "     * Vencimiento: 11/25"
echo "     * Nombre: APRO"
echo ""
echo "5. Para probar webhooks en local, usa ngrok:"
echo "   ngrok http 8000"
echo "   Luego configura la URL de webhook en Mercado Pago"
echo ""
echo "📖 Lee MERCADOPAGO_README.md para más detalles"
echo ""
